ALTER SESSION SET CURRENT_SCHEMA = SamataR;

CREATE TABLE Student(
StudentID VARCHAR2(10) NOT NULL,
StudentName VARCHAR2(30) NOT NULL,
StudentDOB DATE,
StudentAge INTEGER CHECK (StudentAge>=7),
ContactNumber VARCHAR2(15),
EmailID VARCHAR2(30),
CONSTRAINT PK_Student PRIMARY KEY (StudentID)
);

CREATE TABLE Course(
CourseID VARCHAR2(15) NOT NULL,
CourseName VARCHAR2(30) NOT NULL,
CourseStartDate DATE,
CourseEndDate DATE,
CourseFees VARCHAR2(10),
CONSTRAINT PK_Course PRIMARY KEY (CourseID)
);

CREATE TABLE Student_Course(
StudentID VARCHAR2(10) NOT NULL,
CourseID VARCHAR2(30) NOT NULL,
CONSTRAINT FK_StudentID FOREIGN KEY (StudentID) REFERENCES Student (StudentID),
CONSTRAINT FK_CourseID FOREIGN KEY (CourseID) REFERENCES Course (CourseID)
);

CREATE TABLE Subject(
SubjectID VARCHAR2(30) NOT NULL,
SubjectName VARCHAR2(50) NOT NULL,
CONSTRAINT PK_Subject PRIMARY KEY (SubjectID)
);

CREATE TABLE Course_Subject(
CourseID VARCHAR2(30) NOT NULL,
SubjectID VARCHAR2(30) NOT NULL,
CONSTRAINT FK_CourseSubjectID FOREIGN KEY (CourseID) REFERENCES Course (CourseID),
CONSTRAINT FK_SubjectID FOREIGN KEY (SubjectID) REFERENCES Subject (SubjectID)
);

CREATE TABLE Student_Attendance(
StudentID VARCHAR2(10) NOT NULL,
SubjectID VARCHAR2(30) NOT NULL,
AttendanceDate DATE,
Attendance VARCHAR2(1) DEFAULT 'N',
CONSTRAINT FK_AttStudentID FOREIGN KEY (StudentID) REFERENCES Student (StudentID),
CONSTRAINT FK_AttSubjectID FOREIGN KEY (SubjectID) REFERENCES Subject (SubjectID)
);

CREATE TABLE Student_Marks(
StudentID VARCHAR2(10) NOT NULL,
SubjectID VARCHAR2(30) NOT NULL,
Semester VARCHAR2(2) NOT NULL,
SemMarks VARCHAR2(3) NOT NULL,
Pass VARCHAR2(1) DEFAULT 'Y',
CONSTRAINT FK_MarksStudentID FOREIGN KEY (StudentID) REFERENCES Student (StudentID),
CONSTRAINT FK_MarksSubjectID FOREIGN KEY (SubjectID) REFERENCES Subject (SubjectID)
);